/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoofRouteImport } from './routes/roof'
import { Route as PorchRouteImport } from './routes/porch'
import { Route as EnvRouteImport } from './routes/env'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const RoofRoute = RoofRouteImport.update({
  id: '/roof',
  path: '/roof',
  getParentRoute: () => rootRouteImport,
} as any)
const PorchRoute = PorchRouteImport.update({
  id: '/porch',
  path: '/porch',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvRoute = EnvRouteImport.update({
  id: '/env',
  path: '/env',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalog': typeof CatalogRoute
  '/env': typeof EnvRoute
  '/porch': typeof PorchRoute
  '/roof': typeof RoofRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalog': typeof CatalogRoute
  '/env': typeof EnvRoute
  '/porch': typeof PorchRoute
  '/roof': typeof RoofRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalog': typeof CatalogRoute
  '/env': typeof EnvRoute
  '/porch': typeof PorchRoute
  '/roof': typeof RoofRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/catalog' | '/env' | '/porch' | '/roof'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/catalog' | '/env' | '/porch' | '/roof'
  id: '__root__' | '/' | '/about' | '/catalog' | '/env' | '/porch' | '/roof'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CatalogRoute: typeof CatalogRoute
  EnvRoute: typeof EnvRoute
  PorchRoute: typeof PorchRoute
  RoofRoute: typeof RoofRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roof': {
      id: '/roof'
      path: '/roof'
      fullPath: '/roof'
      preLoaderRoute: typeof RoofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/porch': {
      id: '/porch'
      path: '/porch'
      fullPath: '/porch'
      preLoaderRoute: typeof PorchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/env': {
      id: '/env'
      path: '/env'
      fullPath: '/env'
      preLoaderRoute: typeof EnvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CatalogRoute: CatalogRoute,
  EnvRoute: EnvRoute,
  PorchRoute: PorchRoute,
  RoofRoute: RoofRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
